### ISSUE TITLE
Use Example in README.MD Gives Error

### ISSUE THREAD

**Issue by devinbmiller** [NITDgpOS/PlotIt#105]
The following example in README.md:
**python plotit.py -f cos(x)**

Gives me the following error:
**zsh: no matches found: cos(x)**

This is corrected by:
**python plotit.py -f 'cos(x)'**

**Comment by djmgit** [comment]
Nice catch, please send a PR to correct it if you are interested :)

**Comment by devinbmiller** [comment]
I will work on it.

**Comment by djmgit** [comment]
closing this as this has been fixed.
