### ISSUE TITLE
Plot points from list of x and y coordinates

### ISSUE THREAD

**Issue by Aniq55** [NITDgpOS/PlotIt#18]
`python plotit.py -l [x1,x2,x3,x4,x5,...,xN],[y1,y2,y3,y4,y5,...,yN]`

Note that x1 x2 x3 ... are numbers and separated only by a comma, there is no space in between

**Comment by LoneOne123** [comment]
@djmgit @Aniq55 
i had a look at this, not sure if thats a good solution but work for now
as u can see in plotutil i duplicate the plot function, and modified it a bit for the points, cause of the points we dont need a start and end point or the steps option with -l option instead of -f
greets

**Comment by Aniq55** [comment]
@LoneOne123 nice attempt. Please add a condition to check whether the number of x points equals the number of y points or not and also force the sclaing to: `x_limits= [min(x), max(x)]` and `y_limits= [min(y), max(y)]` when `xstart`, `xend` values are not provided by the user

**Comment by LoneOne123** [comment]
@Aniq55 sry was busy...
so now i bring up a check for equal values in the arrays, and changed the datatype from int to float think thats more practical maybe someone wants to display float numbers.
but the x_limit and y_limit thing i dont understand, cuz the pyplot lib does it as default, here to screens
with: python plotit.py -l '[-100,2,3,400],[100.4,2.9,-300.3,50]' -c green
![xylimits](https://user-images.githubusercontent.com/33137583/32981328-627d47f8-cc75-11e7-976b-6ca073fc8997.png)
and with: python plotit.py -l '[-1000,2,3,4000],[1000.4,2.9,-3000.3,50]' -c green
![xylimitsbigger](https://user-images.githubusercontent.com/33137583/32981416-df8a5e98-cc75-11e7-8449-9ec7b0bfdae4.png)
thats why xstart and xend is senseless with the use of points, or am i wrong?

**Comment by Aniq55** [comment]
@LoneOne123  I think it's perfect now. Do send in a PR with a single commit. And no need to say sorry, there are no deadlines in Open Source. (:

**Comment by djmgit** [comment]
@LoneOne123 nice going, please send a PR as @Aniq55 has already mentioned. We can iterate on this :+1:
