### ISSUE TITLE
Add a drop down for choosing colors.

### ISSUE THREAD

**Issue by djmgit** [NITDgpOS/PlotIt#29]
![graph](https://user-images.githubusercontent.com/16368427/31873316-1162b7a8-b7e0-11e7-98a6-438afd2744f4.png)

Presently users have to choose colours from a list of radio buttons. Although it works fine, but the problem with this approach is that the list takes up a lot of space which could have been used otherwise. The goal of this issue is to replace the list of radio buttons by a drop down. As in a drop down the list will appear on demand, space will be saved.

Please refer to the suggestion made by @Aniq55 in #28

**Comment by LoneOne123** [comment]
hey, thats another one i can fix, 
but i would do it not exactly like @Aniq55 mentioned in #28 
i think we can save the button, so when u pick a color from the dropdown menu it changes the inputifeld of the hex color to the color choosen in the dropdown, and when u click go it changes the color to the its inside the inputfield, so u can choose color from the dropdown OR choose a 'custom' one.
is that a good idea or do u want the second button?
and what colors the dropdown should have? the same like the radiobuttons or more?

**Comment by LoneOne123** [comment]
have a look at it, thats how i meant it, if it's fine i would do a pr, should i do another button like Aniq55 mentioned?
didn't get an answer so i just experimented a bit for practice ...
greets

**Comment by djmgit** [comment]
@LoneOne123 can you please send a PR so that we can test it out once, after that we can let you know how it looks like. And apologies for taking so long to reply, was busy with some other stuff.

**Comment by Aniq55** [comment]
@LoneOne123 that's fine. Don't forget to add a screenshot in the comments of your PR.
