### ISSUE TITLE
Add feature to plot function on pressing enter in GUI mode

### ISSUE THREAD

**Issue by djmgit** [NITDgpOS/PlotIt#30]
After entering the function, user should be able to plot the function by pressing enter also.

**Comment by LoneOne123** [comment]
Hi, I would solve this (will be my first contribution)
And I noticed another thing the text color of the input fields is nearly white on white background so when u enter something it's nearly impossible to read it. Should I open another issue for that?

**Comment by djmgit** [comment]
@LoneOne123 its great that you want to contribute, welcome on board. Please go head with this issue. Assigning you to this.
As of the issue you mentioned, please could you point out which input field you are talking about?

**Comment by LoneOne123** [comment]
All input fields, I'm home in some hours then I will show u Screenshots

**Comment by LoneOne123** [comment]
so here thats what i mean
![_screen](https://user-images.githubusercontent.com/33137583/32129194-be9fe786-bb84-11e7-81cc-5fea71050ae0.png)

**Comment by djmgit** [comment]
@LoneOne123 what OS are you using?

**Comment by LoneOne123** [comment]
Ubuntu or better kubuntu

**Comment by Aniq55** [comment]
@djmgit can we open an issue for Light/Dark theme switch?

**Comment by djmgit** [comment]
@Aniq55 sure!!
