### ISSUE TITLE
Implement a DarkTheme/LightTheme switch

### ISSUE THREAD

**Issue by djmgit** [NITDgpOS/PlotIt#32]
Implement a dark theme for the app and finally add a gui switch to toggle between the two themes.

**Comment by LoneOne123** [comment]
@djmgit i will give it a try, do you have any ideas of the colors for light and light/dark theme because atm it's a bit mixed its light and dark at the same time

**Comment by LoneOne123** [comment]
well ok i've done something so here my suggestions,
here the gui in dark and white:
![darktheme](https://user-images.githubusercontent.com/33137583/32997593-5926fc6c-cd92-11e7-9786-195a49fd7a3e.png)
![lighttheme](https://user-images.githubusercontent.com/33137583/32997595-5e353426-cd92-11e7-8d1c-3750f4034b90.png)
and for terminal version samthing with option -t ;)
what u think about it?
i noticed now the buttons on dark theme could be a bit brighter but that wouldnt be a problem :)
greets

**Comment by Aniq55** [comment]
Looks great @LoneOne123 send in a PR for review.

**Comment by djmgit** [comment]
@LoneOne123 can you please post your mail-id over here?

And I agree with @Aniq55 , screenshots are looking great, waiting for a PR :+1:

**Comment by LoneOne123** [comment]
I have sent u an email ;)

**Comment by rahuldcoder** [comment]
there is a typo in line 204 of gui_main.py which is stopping from getting back to the light theme.
',' should be replaced by '.'

**Comment by djmgit** [comment]
@rahuldcoder thanks a lot for spotting the error. can you please create an issue for the same and send a PR?

**Comment by ankan17** [comment]
Isn't this feature already implemented? Shouldn't this issue be closed? @djmgit

**Comment by djmgit** [comment]
@ankan17 yes you are right, closing this.
