### ISSUE TITLE
Allow usage of symbols to plot a function from terminal.

### ISSUE THREAD

**Issue by djmgit** [NITDgpOS/PlotIt#47]
User should be able to use symbols to plot the function instead of always using solid line. Matplotlib allows certain symplos like dashed line, dots etc to plot functions. PlotIt should also be able to use those symbols from terminal. Add a switch for the same so that the symbol can be passed as a parameter from command line.

**Comment by ankan17** [comment]
Can you please elaborate which symbols are you talking about? @djmgit

**Comment by djmgit** [comment]
@ankan17 please check what symbols are provided by matplotlip
As far I remember, they allow dashes '-' , dots '.', and a few more. Please checkout the options provided by matplotlip. Add a suitable switch. User should be able to use it in the following way:

```python plotit.py -f x --symbol -```

**Comment by aditodkar** [comment]
@djmgit I will work on this issue.

**Comment by aditodkar** [comment]
This issue can be closed @djmgit
