### ISSUE TITLE
The plot is not enlarged when the window is zoomed.

### ISSUE THREAD

**Issue by djmgit** [NITDgpOS/PlotIt#48]
### Steps to reproduce:
- Launch the GUI.
- Enter a function and plot it.
- Maximise the window.
- The plot does not get maximised.

### Desired behaviour
- The plot should also get maximised.

Please maximise the plot on expanding window.

**Comment by ankan17** [comment]
I would like to work on this issue

**Comment by djmgit** [comment]
@ankan17 please go ahead,  will assign you ASAP
