### ISSUE TITLE
Add a menubar.

### ISSUE THREAD

**Issue by djmgit** [NITDgpOS/PlotIt#49]
Presently PlotIt does not have any menu bar. Soon we will be requiring a menu bar to group menus and options. Add a menu bar. As of now, add two menus: File and Help. Help will be dummy as of now. Under file there will be one option: Quit, clicking on which will close the app.

**Comment by aditodkar** [comment]
I would like to work on this issue can you assign it to me. I am familiar with python and tkinter.

**Comment by djmgit** [comment]
@aditodkar Sure, please go ahead :+1:

**Comment by djmgit** [comment]
@aditodkar Github will not allow me to assign you unless you have sent atleast one PR to this repo, don not worry, this issue has been claimed by, please start working, good luck :)

**Comment by aditodkar** [comment]
Can we close this now. Please clarify my doubt on gitter please.
