### ISSUE TITLE
Add a feature to plot a discrete number of points using a given function from terminal.

### ISSUE THREAD

**Issue by djmgit** [NITDgpOS/PlotIt#50]
User should be able to provide a function and a set of discrete x points. The function will be plotted for only those points rather than a continuous range. The points should be provided using a switch. Something like
``` python plotit.py -f x**2 -x [10,100,200] ``` The function should be provided for only the provided x points.

**Comment by ankan17** [comment]
I would like to work on this issue @djmgit

**Comment by ankan17** [comment]
Also I'd like to make --xpoints and the group of --xstart, --xend and --stepsize mutually exclusive as they do the same job
