### ISSUE TITLE
Typo error comma in place of period 

### ISSUE THREAD

**Issue by rahuldcoder** [NITDgpOS/PlotIt#51]
There is a syntax error on line 204 of the gui_main.py file which is prohibiting the switching back to light theme.

**Comment by djmgit** [comment]
@raholcoder would you like to work on it?

**Comment by rahuldcoder** [comment]
Ya sure

**Comment by djmgit** [comment]
@rahuldcoder great, assigning this to you :+1:

**Comment by djmgit** [comment]
@rahuldcoder thanks a lot for working on this, look forward to more contributions for you :)

**Comment by rahuldcoder** [comment]
Definitely looking forward.
