### ISSUE TITLE
Use flake8 to lint the code.

### ISSUE THREAD

**Issue by djmgit** [NITDgpOS/PlotIt#55]
Use flake8 to lint the code. The code should be made PEP8 compliant. The objective of this issue will be to add flake8 and add the necessary rules. Initially there might be lots of violations, but those can be solved in the subsequent PRs.

**Comment by ankan17** [comment]
I am interested in doing this

**Comment by djmgit** [comment]
@ankan17 great, please go ahead :+1:

**Comment by djmgit** [comment]
@ankan17 I am not sure why, but I am unable to assign you to this issue, but thats not a problem, please go ahead with this issue :)

**Comment by Aniq55** [comment]
@djmgit you can assign issues to members of NITDgpOS and the person who created the issue. So you can ask people to open issues to be able to assign it to them.
