### ISSUE TITLE
Tries to plot the function even if no function is provided when changing theme

### ISSUE THREAD

**Issue by ankan17** [NITDgpOS/PlotIt#58]
Following error is generated when function is left blank and theme is changed from dark to light or vice-versa.

```
***** Plot Summary *****
Funtion: 
Starting abcissa: 0
Ending abcissa: 100
Step size: 1.0
Color: #FF0000
X-label: X-axis
Y-label: Y-axis
Function cannot be evaluated for x = 0
An error occured.
```

**Comment by ankan17** [comment]
@djmgit Please add the appropriate labels and assign this issue to me :)

**Comment by djmgit** [comment]
@ankan17 please go ahead with this issue, currently away from my keyboard,  will assign you once i am back

**Comment by djmgit** [comment]
closing this.
