### ISSUE TITLE
Display the function in the plot

### ISSUE THREAD

**Issue by Aniq55** [NITDgpOS/PlotIt#77]
* Suppose the function is `f(x)= x^2+ e^(-x)+5`
* On the plot of the function, in one line the function should be displayed as:
$$ f(x)=x^2+ e^{-x}+5 $$, the $$ signinfy LaTeX equation view.
* Matplotlib supports it by default.

**Comment by aditodkar** [comment]
I will work on this.

**Comment by djmgit** [comment]
@aditodkar Please go ahead :+1:
