### ISSUE TITLE
Not quitting properly from "Quit " option in filemenu

### ISSUE THREAD

**Issue by realsdx** [NITDgpOS/PlotIt#93]
Not quitting properly from "Quit " option in filemenu **after plotting a figure**, it makes the command line unusable, CTRL-C/CTRL-D doesn't work ... the only way out is CTRL-Z (suspend).
Fixed this.. but don't know what actually caused this in the first place.
![screenshot from 2018-02-02 08-46-11](https://user-images.githubusercontent.com/30264618/35715030-248da9e4-07f6-11e8-8ca9-7da489071168.png)

**Comment by realsdx** [comment]
will make a PR soon.

**Comment by djmgit** [comment]
@realsdx can you please mention the exact steps to reproduce this bug. 
I used the quit option from file menu, and its shutting down the app with out any trouble.

**Comment by realsdx** [comment]
but if i don't plot anything and use the filemenu quitting option.. then it works fine

**Comment by djmgit** [comment]
@realsdx got it, so after plotting, quit functionality is breaking.
Please go ahead with it and send a PR.
Thanks for pointing it out :)

**Comment by djmgit** [comment]
I have assigned this to you :)

**Comment by realsdx** [comment]
Sorry for the LATE PR __/\__.

**Comment by djmgit** [comment]
closing this via #106
